FROM alpine:latest
ARG NEOFORGE_VERSION="21.1.206"
RUN apk add --no-cache openjdk21
RUN apk add --no-cache rcon
COPY rootfs/ /
WORKDIR /opt/neoforge-installer
RUN wget https://maven.neoforged.net/releases/net/neoforged/neoforge/${NEOFORGE_VERSION}/neoforge-${NEOFORGE_VERSION}-installer.jar
RUN java -jar neoforge-${NEOFORGE_VERSION}-installer.jar --install-server /opt/mc-server --server-jar \
    && chmod 755 /opt/mc-server/start.sh \
    && chmod 755 /opt/mc-server/setup-server-properties.sh
WORKDIR /opt/server-runtime
ENTRYPOINT [ "/opt/mc-server/start.sh" ]
