services:
  foundry-vtt:
    image: local/foundry-vtt:13.346
    init: true
    environment:
      SSL_ENABLED: "false"
      SSL_CERT: ""
      SSL_KEY: ""
    ports:
    - 127.0.0.1:30000:30000/tcp
    volumes:
    - foundry-vtt-data:/opt/foundry-vtt-data
volumes:
  foundry-vtt-data: