services:
  foundry-vtt:
    image: local/foundry-vtt:13.346
    init: true
    environment:
      SSL_ENABLED: "true"
    ports:
      - 127.0.0.1:443:30000/tcp
    volumes:
      - type: bind
        source: ./data
        target: /opt/foundry-vtt-data
