services:
  mc-server:
    image: local/fabric-mc:0.16.10
    init: true
    environment:
      MEMORY: "8192"
      ACCEPT_EULA: "true"
      ALLOW_FLIGHT: "true"
      DIFFICULTY: "hard"
      ENABLE_COMMAND_BLOCK: "true"
      ENFORCE_SECURE_PROFILE: "false"
      ENFORCE_WHITELIST: "true"
      MAX_PLAYERS: "3"
      MOTD: "Local §6Prominence §6II §6RPG§r Server"
    ports:
      - 10.0.0.127:25565:25565/tcp
    volumes:
      - type: bind
        source: ./runtime
        target: /opt/server-runtime

